services:
  backend:
    build: backend
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    environment:
      - JWT_KEY=secret
  frontend:
    build: frontend
  nginx:
    image: nginx
    ports:
      - 3000:80
    volumes:
      - type: bind
        source: nginx.conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

    
