services:
  backend:
    build: backend
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    environment:
      - JWT_KEY=secret
  frontend:
    build: frontend
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    # volumes:
    #   - type: bind
    #     source: /pgdata
    #     target: /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=simple_inventory
  minio:
    image: minio/minio:RELEASE.2024-07-04T14-25-45Z-cpuv1
    ports:
      - 9000:9000
      - 9001:9001
    # volumes:
    #   - type: bind
    #     source: /data
    #     target: ~/minio/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniopassword
    command: server /data --console-address ":9001"
  nginx:
    image: nginx:1.27
    ports:
      - 3000:80
    volumes:
      - type: bind
        source: nginx.conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
