"""Make item.extern_id nullable

Revision ID: 137b13a0336b
Revises: 72760dfd7a3c
Create Date: 2024-07-30 19:05:12.047363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '137b13a0336b'
down_revision: Union[str, None] = '72760dfd7a3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'external_id',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'external_id',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
