"""Make item.location_comment nullable

Revision ID: 224a66daec38
Revises: 137b13a0336b
Create Date: 2024-07-30 22:02:21.427706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '224a66daec38'
down_revision: Union[str, None] = '137b13a0336b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'location_comment',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'location_comment',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
